repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.3
  hooks: 
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format
- repo: https://github.com/psf/black
  rev: 24.5.0
  hooks: 
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks: 
    - id: mypy
      additional_dependencies: [types-PyYAML, types-python-dateutil]
- repo: local
  hooks:
    - id: golden-csv-validation
      name: Validate against golden CSVs
      entry: python golden_validator.py
      language: system
      files: '\.csv$'
      exclude: '^golden_.*\.csv$'
