name: Nightly Validation

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:     # Allow manual trigger

jobs:
  full-corpus-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,ai]"
    
    - name: Run AI-enhanced parser on full corpus
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python ai_enhanced_parser.py --batch-mode --all-pdfs
    
    - name: Generate comprehensive report
      run: |
        python scripts/generate_nightly_report.py
    
    - name: Create issue if accuracy drops
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Nightly validation failed',
            body: 'Parser accuracy dropped below threshold. Check artifacts.',
            labels: ['bug', 'accuracy']
          })
    
    - name: Upload validation artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: nightly-validation
        path: |
          validation_report.json
          all_pdfs_output/
          logs/
